name: Yesterday Mereged PRs
decription: Yesterday Mereged PRs to ISSUE.
outputs:
  csv:
    description: Summary(csv)
    value: ${{ steps.rawdata.outputs.data }}

runs:
  using: composite
  steps:
    - name: Get repository metrics
      id: rawdata
      shell: bash
      run: |
        # mdate=$(date '+%Y-%m-%d' -d '-1 day')
        mdate=$(date '+%Y-%m-%d')
        owner=$(echo ${{ github.repository }} | awk -F '/' '{print $1}')
        repos=$(echo ${{ github.repository }} | awk -F '/' '{print $2}')
        gh extension install hectcastro/gh-metrics
        data="$(gh metrics --owner "$owner" --repo "$repos" --start "$mdate" --end "$mdate" --only-weekdays --csv)"
        data="${data//$'\n'/'%0A'}"
        echo "::set-output name=data::$data"
        echo "::set-output name=mdate::$mdate"
      env:
        TZ: Asia/Tokyo
        GH_TOKEN: ${{ github.token }}

    - name: Create markdown
      id: markdown
      shell: bash
      run: |
        table="| PR | LeadTime | TimeTo1stReview | ReviewTimeTotal | Additions | Deletions | ChangedFiles | "
        table="$table\\n| -- | --------- | ------------- | --------- | ------------------ | ------------ | -- |"
        IFS=$'\n';
        for row in $(echo "${{ steps.rawdata.outputs.data }}" | tail -n +2)
        do
          num="$(echo $row | cut -d, -f1)"
          add="$(echo $row | cut -d, -f3)"
          del="$(echo $row | cut -d, -f4)"
          changed="$(echo $row | cut -d, -f5)"
          leadTime="$(echo $row | cut -d, -f9)"
          timeToFirstReiew="$(echo $row | cut -d, -f6)"
          reviewTimeTotal="$(echo $row | cut -d, -f10)"
          table="$table\\n| __#$num__ | __$leadTime__ | __$timeToFirstReiew__ | __$reviewTimeTotal__ | __$add__ line | __$del__ line | __$changed__ file |"
        done
        echo "$table"
        table="${table//'%'/'%25'}"
        table="${table//$'\n'/'%0A'}"
        table="${table//$'\r'/'%0D'}"
        echo "::set-output name=table::$table"

    - name: Create report
      shell: bash
      run: |
        body="${{ steps.markdown.outputs.table }}"
        gh issue create -R ${{ github.repository }} --body "$(echo -e $body)" --title "Merged At ${{ steps.rawdata.outputs.mdate }} PRs"
      env:
        GH_TOKEN: ${{ github.token }}
